
# Rez deps paths

file(TO_CMAKE_PATH $ENV{BOOST_ROOT} BOOST_ROOT)
file(TO_CMAKE_PATH $ENV{BOOST_INCLUDE_DIR} BOOST_INCLUDEDIR)


file(TO_CMAKE_PATH $ENV{LIBJPEG_TURBO_LIBRARY_DIR} OPENJPEG_LIBRARY)
file(TO_CMAKE_PATH $ENV{LIBJPEG_TURBO_INCLUDE_DIR} OPENJPEG_INCLUDE_DIR)
file(TO_CMAKE_PATH $ENV{LIBJPEG_TURBO_ROOT} JPEGTURBO_PATH)

# Cycles options

set(WITH_CPU_SSE ON)
set(WITH_CYCLES_STANDALONE_GUI OFF)

set(WITH_CYCLES_OSL OFF)
set(WITH_CYCLES_OPENCOLORIO ON)
set(WITH_CYCLES_OPENSUBDIV ON)
set(WITH_CYCLES_OPENVDB ON)

set(WITH_CYCLES_EMBREE ON)

set(WITH_CYCLES_LOGGING OFF)
set(WITH_CYCLES_DEBUG OFF)

set(WITH_CYCLES_CUDA_BINARIES OFF)

# TODO: These might not be set properly. Denoise still seems to print ON in console
set(WITH_CYCLES_OPENIMAGEDENOISE OFF)
